spring:
  application:
    name: swimming-pool-discovery-client
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: localhost
    